---

- hosts: all
  become: true
  tasks:

  - name: install Nginx
    apt:
      name: nginx

  - name: Install Apache2
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest

  - name: update repository index
    apt:
     update_cache: yes

