---

- hosts: all
  become: true
  tasks:

  - name: Install Apache2, Nginx, php package and also update cache
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package}}"
        - "{{ nginx_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

