---

- hosts: all
  become: true
  tasks:

  - name: remove Nginx
    apt:
      name: nginx
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent

  - name: update repository index
    apt:
     update_cache: yes

  - name: remove Apache2
    apt:
      name: apache2
      state: absent
